name: RankAnimator
version: '${version}'
main: io.github.ItsRavensLand.rankAnimator.RankAnimator
api-version: '1.21'
description: Animated rank prefixes in TAB using LuckPerms groups
authors: [ItsRavensLand]

depend:
  - LuckPerms
  - PlaceholderAPI

softdepend:
  - TAB

commands:
  rankanimator:
    description: RankAnimator main command
    aliases: [ra]
    permission: rankanimator.admin
    usage: /rankanimator <reload>

permissions:
  rankanimator.admin:
    description: Access to RankAnimator admin commands
    default: op
